hide caffe2 related code from oss
Summary:
We have an internal dependency:
```
d2go/export/logfiledb.py", line 8, in <module>
    from mobile_cv.torch.utils_caffe2.ws_utils import ScopedWS
    ModuleNotFoundError: No module named 'mobile_cv.torch'
```
This cause the failure of unittest on GitHub
https://github.com/facebookresearch/d2go/pull/58/checks?check_run_id=2471727763

Differential Revision: D28109444

fbshipit-source-id: f2fbc89fad55354c9f3388c7875bda14652d53a5