not block if assertion error when counting flops
Summary:
fvcore flops calculator throws on this error:

KeyError: 'Only support flattening dictionaries if keys are str.'

Setting flops to some value so it doesn't enter pdb mode.

Reviewed By: stephenyan1231

Differential Revision: D32144492

fbshipit-source-id: 604cd4660cea9ffbfb3f1da35d32e06ccf607a50